### ISSUE TITLE
Merci de Verifier l'élement body au niveau de css

### ISSUE THREAD

**Issue by NoureddineMa** [IronSteel007/D-velopper-l-interface-statique-du-restaurant-YouCode#5]
(body {
  background-color: rgb(255, 247, 236);
})

**Comment by aslukili** [comment]
il n'y a rien de tel
donne nous le numéro de la ligne
J'ai utilisé ctrl + f pour trouver cela mais il n'y a rien

**Comment by NoureddineMa** [comment]
@el-ouakili  
![image](https://user-images.githubusercontent.com/93933264/148617798-b9bed99b-9458-42a3-ba89-32579498da65.png)
